[package]
name = "models"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
burn = { version = "0.14", default-features = false, features = ["autodiff", "std"] }

[features]
default = ["tinydet"]
tinydet = []
bigdet = []
